const images = {
  call: require('../assets/Icons/call.png'),
  message: require('../assets/Icons/message.png'),
  dial: require('../assets/Icons/dial.png'),
  team: require('../assets/Icons/team.png'),
  contacts: require('../assets/Icons/contacts.png'),
  info: require('../assets/Icons/info.png'),
  addTeam: require('../assets/Icons/addTeam.png'),
  contactCall: require('../assets/Icons/contactCall.png'),
  contactChat: require('../assets/Icons/contactChat.png'),
  starIcon: require('../assets/Icons/starIcon.png'),
  callButton: require('../assets/Icons/callButton.png'),
  backSpace: require('../assets/Icons/backSpace.png'),
  voicemail: require('../assets/Icons/voicemail.png'),
  voicemail_clear: require('../assets/Icons/voicemail_clear.png'),
  caretLeft: require('../assets/Icons/caretLeft.png'),
  caretRight: require('../assets/Icons/caretRight.png'),
  creditIcon: require('../assets/Icons/creditIcon.png'),
  cross: require('../assets/Icons/cross.png'),
  edit: require('../assets/Icons/edit.png'),
  logout: require('../assets/Icons/logout.png'),
  profile: require('../assets/Icons/profile.png'),
  settings: require('../assets/Icons/settings.png'),
  troubleshooting: require('../assets/Icons/troubleshooting.png'),
  play: require('../assets/Icons/play.png'),
  pause: require('../assets/Icons/pause.png'),
  note: require('../assets/Icons/note.png'),

  // Login
  leftImage: require('../assets/Login/leftImage.png'),
  qrCode: require('../assets/Login/qrCode.png'),
  unidenLogo: require('../assets/Login/unidenLogo.png'),
  zianLogo: require('../assets/Login/zianLogo.png'),
};
export default images;
