import {TABLES, COLUMNS, INDEXES} from './DatabaseTypes';

export const DATABASE_SCHEMA = {
  [TABLES.SETTINGS]: {
    create: `CREATE TABLE IF NOT EXISTS ${TABLES.SETTINGS} (
      ${COLUMNS.SETTINGS.ID} INTEGER PRIMARY KEY AUTOINCREMENT,
      ${COLUMNS.SETTINGS.ACTIVE} INTEGER DEFAULT 1,
      ${COLUMNS.SETTINGS.BETTYPE} TEXT,
      ${COLUMNS.SETTINGS.CNT} TEXT,
      ${COLUMNS.SETTINGS.PERC} TEXT,
      ${COLUMNS.SETTINGS.MAXLENGTH} INTEGER DEFAULT 3,
      ${COLUMNS.SETTINGS.DIVISIBLE} INTEGER DEFAULT 0,
      ${COLUMNS.SETTINGS.START11} INTEGER,
      ${COLUMNS.SETTINGS.START11M} INTEGER,
      ${COLUMNS.SETTINGS.END11} INTEGER,
      ${COLUMNS.SETTINGS.END11M} INTEGER,
      ${COLUMNS.SETTINGS.START4} INTEGER,
      ${COLUMNS.SETTINGS.START4M} INTEGER,
      ${COLUMNS.SETTINGS.END4} INTEGER,
      ${COLUMNS.SETTINGS.END4M} INTEGER,
      ${COLUMNS.SETTINGS.START9} INTEGER,
      ${COLUMNS.SETTINGS.START9M} INTEGER,
      ${COLUMNS.SETTINGS.END9} INTEGER,
      ${COLUMNS.SETTINGS.END9M} INTEGER,
      ${COLUMNS.SETTINGS.LIMITS} INTEGER DEFAULT 10,
      ${COLUMNS.SETTINGS.CAPPING} INTEGER DEFAULT 250,
      ${COLUMNS.SETTINGS.WINTAR} INTEGER,
      ${COLUMNS.SETTINGS.WINRAM} INTEGER,
      ${COLUMNS.SETTINGS.WINRAM2} INTEGER,
      ${COLUMNS.SETTINGS.BETTYPEID} INTEGER,
      ${COLUMNS.SETTINGS.CREATED_AT} TEXT
    )`,
    indexes: [],
  },

  [TABLES.TRANS]: {
    create: `CREATE TABLE IF NOT EXISTS ${TABLES.TRANS} (
      ${COLUMNS.TRANS.ID} INTEGER PRIMARY KEY AUTOINCREMENT,
      ${COLUMNS.TRANS.TRANS_NO} INTEGER,
      ${COLUMNS.TRANS.TICKETCODE} TEXT,
      ${COLUMNS.TRANS.TOTAL} INTEGER,
      ${COLUMNS.TRANS.TRANS_DATA} TEXT,
      ${COLUMNS.TRANS.BETTYPEID} INTEGER,
      ${COLUMNS.TRANS.BETDATE} DATE,
      ${COLUMNS.TRANS.BETTIME} INTEGER,
      ${COLUMNS.TRANS.STATUS} TEXT DEFAULT 'saved',
      ${COLUMNS.TRANS.CREATED_AT} TEXT
    )`,
    indexes: [
      `CREATE INDEX ${INDEXES.TICKETCODE} ON ${TABLES.TRANS} (${COLUMNS.TRANS.TICKETCODE})`,
      `CREATE INDEX ${INDEXES.TRANS_COMPOSITE} ON ${TABLES.TRANS} (${COLUMNS.TRANS.BETDATE}, ${COLUMNS.TRANS.BETTIME}, ${COLUMNS.TRANS.BETTYPEID})`,
      `CREATE INDEX ${INDEXES.TRANS_STATUS} ON ${TABLES.TRANS} (${COLUMNS.TRANS.STATUS})`,
      `CREATE INDEX ${INDEXES.TRANS_CREATED_AT} ON ${TABLES.TRANS} (${COLUMNS.TRANS.CREATED_AT})`,
      `CREATE INDEX ${INDEXES.TRANS_BETDATE_STATUS} ON ${TABLES.TRANS} (${COLUMNS.TRANS.BETDATE}, ${COLUMNS.TRANS.STATUS})`,
      `CREATE INDEX ${INDEXES.TRANS_BETTYPEID_STATUS} ON ${TABLES.TRANS} (${COLUMNS.TRANS.BETTYPEID}, ${COLUMNS.TRANS.STATUS})`,
    ],
  },

  [TABLES.BET]: {
    create: `CREATE TABLE IF NOT EXISTS ${TABLES.BET} (
      ${COLUMNS.BET.ID} INTEGER PRIMARY KEY AUTOINCREMENT,
      ${COLUMNS.BET.TRANSID} INTEGER REFERENCES ${TABLES.TRANS}(${COLUMNS.TRANS.ID}) ON DELETE CASCADE,
      ${COLUMNS.BET.TRANNO} INTEGER,
      ${COLUMNS.BET.BETNUMBER} TEXT,
      ${COLUMNS.BET.BETNUMBERR} TEXT,
      ${COLUMNS.BET.TARGET} INTEGER,
      ${COLUMNS.BET.RAMBOL} INTEGER,
      ${COLUMNS.BET.SUBTOTAL} INTEGER,
      ${COLUMNS.BET.STATUS} TEXT DEFAULT 'saved',
      ${COLUMNS.BET.CREATED_AT} DATE DEFAULT CURRENT_TIMESTAMP
    )`,
    indexes: [
      `CREATE INDEX ${INDEXES.BET_TRANSID} ON ${TABLES.BET} (${COLUMNS.BET.TRANSID})`,
      `CREATE INDEX ${INDEXES.BET_CREATED_AT} ON ${TABLES.BET} (${COLUMNS.BET.CREATED_AT})`,
      `CREATE INDEX ${INDEXES.BET_STATUS} ON ${TABLES.BET} (${COLUMNS.BET.STATUS})`,
    ],
  },

  [TABLES.RESULT]: {
    create: `CREATE TABLE IF NOT EXISTS ${TABLES.RESULT} (
      ${COLUMNS.RESULT.ID} INTEGER PRIMARY KEY AUTOINCREMENT,
      ${COLUMNS.RESULT.BETTYPEID} INTEGER,
      ${COLUMNS.RESULT.RESULT} TEXT,
      ${COLUMNS.RESULT.RESULTR} TEXT,
      ${COLUMNS.RESULT.BETDATE} DATE,
      ${COLUMNS.RESULT.BETTIME} INTEGER,
      ${COLUMNS.RESULT.CREATED_AT} DATE DEFAULT CURRENT_TIMESTAMP
    )`,
    indexes: [
      `CREATE INDEX ${INDEXES.RESULT_COMPOSITE} ON ${TABLES.RESULT} (${COLUMNS.RESULT.BETDATE}, ${COLUMNS.RESULT.BETTIME}, ${COLUMNS.RESULT.BETTYPEID})`,
      `CREATE INDEX ${INDEXES.RESULT_CREATED_AT} ON ${TABLES.RESULT} (${COLUMNS.RESULT.CREATED_AT})`,
      `CREATE INDEX ${INDEXES.RESULT_BETTYPEID} ON ${TABLES.RESULT} (${COLUMNS.RESULT.BETTYPEID})`,
    ],
  },
};

export const INITIAL_DATA = {
  settings: [
    {
      bettype: 'DEFAULTS',
      wintar: '450',
      winram: '75',
      winram2: '150',
      maxlength: 3,
      cnt: '1.5M',
      perc: '78%',
      bettypeid: 1,
      start11: 4,
      start11m: 0,
      end11: 10,
      end11m: 30,
      start4: 11,
      start4m: 10,
      end4: 15,
      end4m: 30,
      start9: 16,
      start9m: 10,
      end9: 20,
      end9m: 30,
      active: 0,
    },
    {
      bettype: 'S3',
      wintar: '450',
      winram: '75',
      winram2: '150',
      maxlength: 3,
      cnt: '1.5M',
      perc: '78%',
      bettypeid: 2,
      start11: 4,
      start11m: 0,
      end11: 13,
      end11m: 45,
      start4: 14,
      start4m: 15,
      end4: 16,
      end4m: 45,
      start9: 17,
      start9m: 10,
      end9: 20,
      end9m: 45,
    },
    {
      bettype: 'STL SWER3',
      wintar: '450',
      winram: '75',
      winram2: '150',
      maxlength: 3,
      cnt: '1.5M',
      perc: '78%',
      bettypeid: 3,
      start11: 4,
      start11m: 0,
      end11: 10,
      end11m: 30,
      start4: 11,
      start4m: 10,
      end4: 15,
      end4m: 30,
      start9: 16,
      start9m: 10,
      end9: 20,
      end9m: 30,
    },
    {
      bettype: 'LOC SWER3',
      wintar: '450',
      winram: '75',
      winram2: '150',
      maxlength: 3,
      cnt: '1.5M',
      perc: '78%',
      bettypeid: 4,
      start11: 4,
      start11m: 0,
      end11: 10,
      end11m: 15,
      start4: 11,
      start4m: 10,
      end4: 15,
      end4m: 15,
      start9: 16,
      start9m: 10,
      end9: 20,
      end9m: 15,
    },
    {
      bettype: 'LAST 2',
      wintar: '450',
      winram: '75',
      winram2: '150',
      maxlength: 2,
      cnt: '1.5M',
      perc: '78%',
      bettypeid: 5,
      start11: 4,
      start11m: 0,
      end11: 10,
      end11m: 30,
      start4: 11,
      start4m: 10,
      end4: 15,
      end4m: 30,
      start9: 16,
      start9m: 10,
      end9: 20,
      end9m: 30,
    },
  ],

  sampleTransaction: {
    trans_no: 1,
    ticketcode: '4064–3336–6537–3166',
    total: 20,
    trans_data: '247 10 10',
    bettypeid: 2,
    betdate: '2023-04-03',
    bettime: 3,
    status: 'synced',
  },

  sampleBet: {
    tranno: 1,
    betnumber: '247',
    betnumberr: '247',
    target: 10,
    rambol: 10,
    subtotal: 20,
  },

  sampleResult: {
    bettypeid: 2,
    result: '247',
    resultr: '247',
    betdate: '2024-04-03',
    bettime: 3,
  },
};
