export const typesConstants = {
  UPDATE: 'TYPES_UPDATE',
  UPDATE_SELECTED_DRAW: 'TYPES_UPDATE_SELECTED_DRAW',
  UPDATE_SELECTED_DATE: 'TYPES_UPDATE_SELECTED_DATE',
  UPDATE_SELECTED_TYPE: 'TYPES_UPDATE_SELECTED_TYPE',
};
