export const userConstants = {
  INIT_REQUEST: "USERS_INIT_REQUEST",
  INIT_SUCCESS: "USERS_INIT_SUCCESS",
  INIT_FAILURE: "USERS_INIT_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  ADD_SUBSCRIBER: "ADD_SUBSCRIBER",
  REMOVE_SUBSCRIBER: "REMOVE_SUBSCRIBER",
  UPDATE_SUBSCRIBER: "UPDATE_SUBSCRIBER",

  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",

  LOGOUT: "USERS_LOGOUT",

  UPDATE_REQUEST: "USERS_UPDATE_REQUEST",
  UPDATE_SUCCESS: "USERS_UPDATE_SUCCESS",
  UPDATE_FAILURE: "USERS_UPDATE_FAILURE",

  SET_RELOAD: "SET_RELOAD",

  SET_ICE_SERVER: "SET_ICE_SERVER",
};
